host = "0.0.0.0"
port = 3000
delay = 1000

[[routes]]
  [routes.request]
    path = "/posts"
    methods = ["GET"]
    headers = []
  [routes.response]
    delay = 3000
    headers = [
      { key = "Content-Type", value = "application/json" }
    ]
    template = "templates/get-posts.json"

[[routes]]
  [routes.request]
    path = "/media/avatar/{file}"
    methods = ["GET"]
  [routes.response]
    headers = [
      { key = "Content-Type", value = "image/svg+xml" }
    ]
    resources = [
      "resources/avatars/25789.svg",
      "resources/avatars/527688.svg",
      "resources/avatars/7896451.svg",
      "resources/avatars/9785412.svg",
      "resources/avatars/25678412.svg"
    ]
